const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const {
  discoverMigrations,
  compareMigrationState,
  applyPendingMigrations,
  MigrationError,
} = require('../server/db/migrations.cjs');

test('migration catalog is exactly the ordered 001-006 target', () => {
  const migrations = discoverMigrations();
  assert.deepEqual(migrations.map(item => item.version), [1, 2, 3, 4, 5, 6]);
  assert.deepEqual(migrations.map(item => item.name), [
    '001_add_users_and_task_ownership.sql',
    '002_add_executions_and_binding_history.sql',
    '003_add_audit_and_sessions.sql',
    '004_finalize_postgres_only_schema.sql',
    '005_add_durable_run_requests.sql',
    '006_add_binding_scoped_sync_generation.sql',
  ]);
  migrations.forEach(item => assert.match(item.checksum, /^[a-f0-9]{64}$/));
});

test('migrations contain every required durable table and critical invariant', () => {
  const sql = discoverMigrations().map(item => item.sql).join('\n');
  for (const table of [
    'app_users',
    'rpa_tasks',
    'rpa_task_executions',
    'rpa_task_binding_history',
    'rpa_task_audit_log',
    'rpa_task_run_requests',
    'app_sessions',
  ]) {
    assert.match(sql, new RegExp(`CREATE TABLE IF NOT EXISTS public\\.${table}`));
  }
  assert.match(sql, /uq_rpa_tasks_active_schedule_uuid/);
  assert.match(sql, /GENERATED BY DEFAULT AS IDENTITY/);
  assert.match(sql, /owner_user_id\s+BIGINT/);
  assert.match(sql, /normalized_status IN \('等待中', '运行中'\)/);
  assert.match(sql, /uq_rpa_task_run_requests_open_task/);
  assert.match(sql, /schedule_bound_at_at_request\s+TIMESTAMPTZ NOT NULL/);
  assert.match(sql, /task_uuid\s+TEXT UNIQUE,/);
  assert.doesNotMatch(sql, /task_uuid\s+TEXT UNIQUE REFERENCES public\.rpa_task_executions/);
  assert.match(sql, /sync_generation BIGINT NOT NULL DEFAULT 0/);
  assert.match(sql, /normalized_status IN \('等待中', '运行中', '未知状态'\)/);
  assert.match(sql, /audit_log_id\s+BIGINT UNIQUE REFERENCES public\.rpa_task_audit_log\(id\) ON DELETE RESTRICT/);
});

test('psql schema snapshot records the exact migration checksums', () => {
  const snapshot = fs.readFileSync(path.resolve(__dirname, '..', 'storage', 'schema.sql'), 'utf8');
  for (const migration of discoverMigrations()) {
    assert.match(snapshot, new RegExp(migration.checksum));
  }
});

test('startup comparison rejects missing, outdated, and rewritten migration history', () => {
  const migrations = discoverMigrations();
  assert.throws(
    () => compareMigrationState(migrations, null),
    error => error instanceof MigrationError && error.code === 'SCHEMA_NOT_INITIALIZED'
  );
  assert.throws(
    () => compareMigrationState(migrations, migrations.slice(0, 2)),
    error => error.code === 'SCHEMA_OUTDATED' && error.currentVersion === 2
  );
  const rewritten = migrations.map(item => ({ ...item }));
  rewritten[0].checksum = '0'.repeat(64);
  assert.throws(
    () => compareMigrationState(migrations, rewritten),
    error => error.code === 'MIGRATION_CHECKSUM_MISMATCH'
  );
  assert.equal(compareMigrationState(migrations, migrations).currentVersion, 6);
});

test('manual runner refuses non-contiguous applied history instead of migrating out of order', async () => {
  const migrations = discoverMigrations();
  const client = {
    released: false,
    async query(sql) {
      const text = String(sql);
      if (text.includes("to_regclass('public.schema_migrations')")) {
        return { rows: [{ table_name: 'schema_migrations' }] };
      }
      if (text.includes('SELECT version, name, checksum, applied_at')) {
        return { rows: [{
          version: 2,
          name: migrations[1].name,
          checksum: migrations[1].checksum,
          applied_at: new Date(),
        }] };
      }
      return { rows: [] };
    },
    release() { this.released = true; },
  };
  const pool = { connect: async () => client };
  await assert.rejects(
    () => applyPendingMigrations(pool, { migrations }),
    error => error.code === 'MIGRATION_HISTORY_GAP'
  );
  assert.equal(client.released, true);
});
