-- Add application identities and evolve the legacy four-column task table in place.
-- All ownership/binding columns intentionally remain nullable so historical tasks
-- stay visible and read-only until users assign them manually.

CREATE TABLE IF NOT EXISTS public.app_users (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name        TEXT NOT NULL,
  avatar_url          TEXT,
  auth_provider       TEXT NOT NULL DEFAULT 'dev',
  feishu_open_id      TEXT,
  feishu_union_id     TEXT,
  feishu_tenant_key   TEXT,
  is_active           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at       TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_app_users_feishu_union_id
  ON public.app_users (feishu_union_id)
  WHERE feishu_union_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_app_users_feishu_tenant_open_id
  ON public.app_users (feishu_tenant_key, feishu_open_id)
  WHERE feishu_tenant_key IS NOT NULL AND feishu_open_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_app_users_active_provider
  ON public.app_users (auth_provider, is_active, display_name);

-- Fresh databases receive the target shape immediately. Existing databases keep
-- their rows and are extended by the ALTER statements below.
CREATE TABLE IF NOT EXISTS public.rpa_tasks (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task                  TEXT NOT NULL,
  start_time            VARCHAR(8) NOT NULL DEFAULT '00:00:00',
  finish_time           VARCHAR(8) NOT NULL DEFAULT '00:00:00',
  bot                   TEXT NOT NULL DEFAULT '未分类',
  created_by_user_id    BIGINT,
  owner_user_id         BIGINT,
  schedule_uuid         TEXT,
  schedule_bound_at     TIMESTAMPTZ,
  tags                  TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  note                  TEXT NOT NULL DEFAULT '',
  version               INTEGER NOT NULL DEFAULT 1,
  last_synced_at        TIMESTAMPTZ,
  sync_error            TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at            TIMESTAMPTZ
);

ALTER TABLE public.rpa_tasks ALTER COLUMN id TYPE BIGINT;
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS created_by_user_id BIGINT;
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS schedule_uuid TEXT;
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS schedule_bound_at TIMESTAMPTZ;
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS note TEXT NOT NULL DEFAULT '';
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.rpa_tasks ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- Convert the legacy application-assigned integer key into a server-assigned
-- BIGINT identity without changing existing values.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_attribute
     WHERE attrelid = 'public.rpa_tasks'::regclass
       AND attname = 'id'
       AND attidentity IN ('a', 'd')
  ) THEN
    ALTER TABLE public.rpa_tasks ALTER COLUMN id DROP DEFAULT;
    ALTER TABLE public.rpa_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END
$$;

SELECT setval(
  pg_get_serial_sequence('public.rpa_tasks', 'id'),
  CASE WHEN MAX(id) IS NULL THEN 1 ELSE MAX(id) END,
  MAX(id) IS NOT NULL
)
FROM public.rpa_tasks;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rpa_tasks_created_by_user') THEN
    ALTER TABLE public.rpa_tasks
      ADD CONSTRAINT fk_rpa_tasks_created_by_user
      FOREIGN KEY (created_by_user_id) REFERENCES public.app_users(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rpa_tasks_owner_user') THEN
    ALTER TABLE public.rpa_tasks
      ADD CONSTRAINT fk_rpa_tasks_owner_user
      FOREIGN KEY (owner_user_id) REFERENCES public.app_users(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_rpa_tasks_version_positive') THEN
    ALTER TABLE public.rpa_tasks
      ADD CONSTRAINT ck_rpa_tasks_version_positive CHECK (version >= 1) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_rpa_tasks_start_time_format') THEN
    ALTER TABLE public.rpa_tasks
      ADD CONSTRAINT ck_rpa_tasks_start_time_format
      CHECK (start_time ~ '^(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$') NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_rpa_tasks_finish_time_format') THEN
    ALTER TABLE public.rpa_tasks
      ADD CONSTRAINT ck_rpa_tasks_finish_time_format
      CHECK (finish_time ~ '^(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$') NOT VALID;
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_rpa_tasks_active_schedule_uuid
  ON public.rpa_tasks (schedule_uuid)
  WHERE deleted_at IS NULL AND schedule_uuid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_rpa_tasks_owner_active
  ON public.rpa_tasks (owner_user_id, updated_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_rpa_tasks_created_by_user
  ON public.rpa_tasks (created_by_user_id);

CREATE INDEX IF NOT EXISTS idx_rpa_tasks_deleted_at
  ON public.rpa_tasks (deleted_at);

CREATE INDEX IF NOT EXISTS idx_rpa_tasks_bot
  ON public.rpa_tasks (bot);

CREATE INDEX IF NOT EXISTS idx_rpa_tasks_tags_gin
  ON public.rpa_tasks USING GIN (tags);

