CREATE TABLE IF NOT EXISTS public.rpa_task_binding_history (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rpa_task_id       BIGINT NOT NULL REFERENCES public.rpa_tasks(id) ON DELETE RESTRICT,
  schedule_uuid     TEXT NOT NULL,
  bound_at          TIMESTAMPTZ NOT NULL,
  unbound_at        TIMESTAMPTZ,
  actor_user_id     BIGINT REFERENCES public.app_users(id) ON DELETE RESTRICT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_rpa_task_binding_history_interval
    CHECK (unbound_at IS NULL OR unbound_at >= bound_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_rpa_task_binding_history_active_task
  ON public.rpa_task_binding_history (rpa_task_id)
  WHERE unbound_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_rpa_task_binding_history_active_schedule
  ON public.rpa_task_binding_history (schedule_uuid)
  WHERE unbound_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_rpa_task_binding_history_task_time
  ON public.rpa_task_binding_history (rpa_task_id, bound_at DESC);

CREATE INDEX IF NOT EXISTS idx_rpa_task_binding_history_schedule_time
  ON public.rpa_task_binding_history (schedule_uuid, bound_at DESC, unbound_at);

CREATE TABLE IF NOT EXISTS public.rpa_task_executions (
  task_uuid               TEXT PRIMARY KEY,
  rpa_task_id             BIGINT NOT NULL REFERENCES public.rpa_tasks(id) ON DELETE RESTRICT,
  schedule_uuid_at_run    TEXT NOT NULL,
  normalized_status       TEXT NOT NULL DEFAULT '未知状态',
  raw_status              TEXT,
  raw_status_name         TEXT,
  trigger_time            TIMESTAMPTZ NOT NULL,
  updated_time            TIMESTAMPTZ,
  end_time                TIMESTAMPTZ,
  job_uuid_list           JSONB NOT NULL DEFAULT '[]'::JSONB,
  source_type             TEXT,
  clients                 JSONB,
  error_remark            TEXT,
  synced_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  idempotent_uuid         UUID,
  started_by_user_id      BIGINT REFERENCES public.app_users(id) ON DELETE RESTRICT,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_rpa_task_executions_idempotent_uuid
  ON public.rpa_task_executions (idempotent_uuid)
  WHERE idempotent_uuid IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_rpa_task_executions_task_trigger
  ON public.rpa_task_executions (rpa_task_id, trigger_time DESC);

CREATE INDEX IF NOT EXISTS idx_rpa_task_executions_schedule_trigger
  ON public.rpa_task_executions (schedule_uuid_at_run, trigger_time DESC);

CREATE INDEX IF NOT EXISTS idx_rpa_task_executions_active
  ON public.rpa_task_executions (rpa_task_id, updated_time DESC NULLS LAST)
  WHERE normalized_status IN ('等待中', '运行中');

CREATE INDEX IF NOT EXISTS idx_rpa_task_executions_retention
  ON public.rpa_task_executions (COALESCE(end_time, trigger_time));
