CREATE TABLE IF NOT EXISTS public.rpa_task_audit_log (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id         BIGINT NOT NULL REFERENCES public.rpa_tasks(id) ON DELETE RESTRICT,
  actor_user_id   BIGINT REFERENCES public.app_users(id) ON DELETE RESTRICT,
  action          TEXT NOT NULL,
  old_value       JSONB,
  new_value       JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rpa_task_audit_log_task_created
  ON public.rpa_task_audit_log (task_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_rpa_task_audit_log_actor_created
  ON public.rpa_task_audit_log (actor_user_id, created_at DESC);

-- Compatible with connect-pg-simple when configured with tableName=app_sessions.
CREATE TABLE IF NOT EXISTS public.app_sessions (
  sid       VARCHAR NOT NULL PRIMARY KEY,
  sess      JSON NOT NULL,
  expire    TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_app_sessions_expire
  ON public.app_sessions (expire);

